In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
results = pd.read_csv("./data/survey_results_public.csv", index_col="ResponseId")
resultsSchema = pd.read_csv("./data/survey_results_schema.csv")

In [3]:
results.head(5)

,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,...,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,Other,...,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,NaN,...,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
4,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,Formal documentation provided by the owner of ...,NaN,...,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Automated testing;Continuous integration (CI) ...,NaN,Appropriate in length,Easy,156000.0
5,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Other;Codecademy;edX,...,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0

In [4]:
languages = "LanguageHaveWorkedWith"
salary = "ConvertedCompYearly"

results.rename(columns={languages: "Languages", salary: "Salary"}, inplace= True)
results.head(5)
results.dropna(subset=["Salary","Languages"], inplace = True)

results = results.loc[:, ["Country","Salary","Languages"]].sort_values(by="Salary")

filtro = (results["Salary"] >= 10000) & (results["Salary"] <= 3e6)
results = results[filtro]
results

,Country,Salary,Languages
ResponseId,,,
67270,Lebanon,10000.0,C#;HTML/CSS;SQL;Visual Basic (.Net)
66691,Suriname,10000.0,HTML/CSS;JavaScript;Ruby
80568,Sri Lanka,10000.0,Bash/Shell (all shells);HTML/CSS;JavaScript;Py...
9571,Nepal,10000.0,HTML/CSS;Java;JavaScript;Python;SQL
21209,Malaysia,10000.0,HTML/CSS;Java;JavaScript;SQL
...,...,...,...
40856,Brazil,2434514.0,Go;HTML/CSS;JavaScript;Ruby;TypeScript
16082,Denmark,2500000.0,Assembly;C;C#;JavaScript;Python
16632,Nigeria,2592024.0,Dart
51183,United States of America,2700000.0,Bash/Shell (all shells);C;C++;Python;R;Rust
88904,United States of America,3000000.0,Bash/Shell (all shells);C++;HTML/CSS;Python;SQL

In [5]:
lg = results["Languages"]
allLanguages = lg[21403].split(";")

"""for row in lg:
    for lang in row.split(";"):
        if lang in allLanguages:
            continue
        else:
            allLanguages.append(lang)"""
            
# Si no hago el if elimino los lenguajes repetidos        
#allLanguages = list(set(allLanguages))

for row in lg:
    for lang in row.split(";"):
        allLanguages.append(lang)
        
allLanguages = list(set(allLanguages))
allLanguages.sort()

meanSalary = pd.DataFrame(data = np.zeros(len(allLanguages)), index=allLanguages , columns=["Salary"])
meanSalary

                         Salary
APL                         0.0
Ada                         0.0
Apex                        0.0
Assembly                    0.0
Bash/Shell (all shells)     0.0
C                           0.0
C#                          0.0
C++                         0.0
Clojure                     0.0
Cobol                       0.0
Crystal                     0.0
Dart                        0.0
Delphi                      0.0
Elixir                      0.0
Erlang                      0.0
F#                          0.0
Flow                        0.0
Fortran                     0.0
GDScript                    0.0
Go                          0.0
Groovy                      0.0
HTML/CSS                    0.0
Haskell                     0.0
Java                        0.0
JavaScript                  0.0
Julia                       0.0
Kotlin                      0.0
Lisp                        0.0
Lua                         0.0
MATLAB                      0.0
Nim                         0.0
OCaml                       0.0
Objective-C                 0.0
PHP                         0.0
Perl                        0.0
PowerShell                  0.0
Prolog                      0.0
Python                      0.0
R                           0.0
Raku                        0.0
Ruby                        0.0
Rust                        0.0
SAS                         0.0
SQL                         0.0
Scala                       0.0
Solidity                    0.0
Swift                       0.0
TypeScript                  0.0
VBA                         0.0
Visual Basic (.Net)         0.0
Zig                         0.0

In [6]:
import re

for lang in allLanguages:
    try:
        mask = results["Languages"].str.contains(re.escape(lang))
        average = results.loc[mask, "Salary"].mean()
        meanSalary.loc[lang, "Salary"] = average
    except Exception:
        print(lang)
meanSalary

                                Salary
APL                      132385.687500
Ada                      101987.839130
Apex                     111123.447183
Assembly                 115184.755862
Bash/Shell (all shells)  111334.168997
C                         99417.346595
C#                        95933.102206
C++                      109191.077789
Clojure                  125818.861446
Cobol                    107928.296943
Crystal                  111541.106509
Dart                      85332.679481
Delphi                    89237.515798
Elixir                   123143.755085
Erlang                   129693.326693
F#                       125494.164948
Flow                     148097.641509
Fortran                  102634.265363
GDScript                  92445.115079
Go                       124079.832066
Groovy                   112406.458204
HTML/CSS                  94800.095454
Haskell                  118287.890344
Java                      98846.298698
JavaScript                98270.616515
Julia                    104963.805930
Kotlin                   108298.595729
Lisp                     120841.380414
Lua                      106901.026855
MATLAB                    92258.970988
Nim                      105409.752137
OCaml                    130042.969957
Objective-C              124715.885988
PHP                       81307.754596
Perl                     119768.706087
PowerShell               100027.159874
Prolog                    97030.518018
Python                   106943.514886
R                        118309.834417
Raku                     119207.648148
Ruby                     124097.467038
Rust                     121512.626702
SAS                       99724.453552
SQL                       99125.611276
Scala                    126773.493721
Solidity                 110398.535070
Swift                    115198.563879
TypeScript               101544.526092
VBA                       86963.065963
Visual Basic (.Net)       86445.918149
Zig                      143109.972973

In [7]:
colors = [
    "#03071E",
    "#370617",
    "#6A040F",
    "#9D0208",
    "#D00000",
    "#DC2F02",
    "#E85D04",
    "#F48C06",
    "#FAA307",
    "#FFBA08"
]

fontdict = {
    'family': 'serif',
    'color':  'darkred',
    'weight': 'normal',
    'size': 16,
}

In [ ]:
%matplotlib qt5

plt.style.use("seaborn")
meanSalary.sort_values(by="Salary", inplace= True)
plt.barh(meanSalary.index, meanSalary["Salary"], color=colors)
plt.vlines(meanSalary["Salary"].mean(), 0 , len(meanSalary["Salary"]), colors="red", linestyles= "dashed", label= "Mean Salary")

plt.title("Programing Languages Yearly Compensation")
plt.xlabel("Mean Salary in $")
plt.ylabel("Programing languages")


plt.gca().xaxis.set_major_formatter('${x:1.0f}')
plt.legend()
plt.tight_layout()
plt.show()